# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Sharry Blogs
email: SharryChooCHN@Gmail.com
description:  I'm a Android developer. Welcome to my page! 
baseurl: "/blogs" # the subpath of your site, e.g. /blog
url: "https://sharrychoo.github.io/blogs/" # the base hostname & protocol for your site
twitter_username: SharryChoo
github_username:  SharryChoo

# Build settings
markdown: kramdown
